[project]
name = "uv-env-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "torch==2.10.0",
    "transformers==5.14.1",
    "trl==1.9.0",
    "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3%2Bcu13torch2.10cxx11abiTRUE-cp312-cp312-linux_x86_64.whl",
    "ninja",
    "packaging",
    "psutil",
]

[tool.uv.sources]
torch = { index = "torch-cu130" }

[[tool.uv.index]]
name = "torch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

